### ISSUE TITLE
tableofcontents and page references 

### ISSUE THREAD

**Issue by ferent** [duckyb/four-souls-rules-booklet#8]
Thanks for rendering the pdf with the new content!.
Not a big deal but somehow the new main.pdf /tableofcontents page index doesn't match with the real pages.
Also all (or most) of the page references at the bottom of the pages at pointing to wrong pages. 
I don't have my laptop here with me to test it and see what is going on with the new render (on holidays atm) 
Thank you in advance.

**Comment by duckyb** [comment]
Thanks for pointing this out, I'll have a look soon

**Comment by duckyb** [comment]
Fixed in 461a981fee8e834a68cdc93cc7737b3b8417cceb
